
# Services or Containers List definition
services:
  db:
    image: mysql:latest
    container_name: mysql-sunny-server
    ports:
      - 3306:3306
    volumes:
      - ./data/:/var/lib/mysql # Mount directory settings (-v option)
    environment:
      - MYSQL_ROOT_PASSWORD=sunny
      - MYSQL_DATABASE=sunny-server
      - MYSQL_USER=sunny_user_server
      - MYSQL_PASSWORD=sunnyPassword
      - TZ=Asia/Seoul
    command: # Command execution
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis_container:
    image: redis
    container_name: redis-sunny-server
    ports:
      - 6379:6379
#  jenkins:
#    image: jenkins/jenkins:lts
#    user: root
#    volumes:
#      - ./jenkins:/var/jenkins_home
#    ports:
#      - 8080:8080
