
# Services or Containers List definition

services:
  mysql:
    container_name: mysql_sunny
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=sunny_admin
      - MYSQL_PASSWORD=sunny_admin_159
      - MYSQL_ROOT_PASSWORD=sunny_admin_1597
      - TZ=Asia/Seoul
    command: # Command execution
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis_container:
    image: redis
    container_name: redis-sunny-server
    ports:
      - 6379:6379
#  jenkins:
#    image: jenkins/jenkins:lts
#    user: root
#    volumes:
#      - ./jenkins:/var/jenkins_home
#    ports:
#      - 8080:8080

