-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/IPwfIhsQusXkAMp
JPJg1HbR8zsJhL4ofNFSPEUj9iSgCgYIKoZIzj0DAQehRANCAASk0e4frECfoTk9
wNYt4Yvq8o3ieFfhDloXilCGXPkyd6TOsrVqZlvurGT6DnbIu/BbpIcetkNotYl5
1GnKjEqx
-----END PRIVATE KEY-----